language: c
compiler:
  - gcc
os:
  - linux
dist: focal
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt install cmake
  - sudo apt install make
  - sudo apt install libsdl2-dev libsdl2-2.0-0
script: make
