language: cpp
compiler:
  - gcc
os:
  - linux
dist: bionic
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt install build-essential
  - sudo apt install cmake
  - sudo apt install libsdl2-dev libsdl2-2.0-0
script: make
